# Generated by Django 5.1.6 on 2025-02-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room', models.CharField(max_length=255)),
                ('services', models.TextField(blank=True, null=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=50)),
                ('card_holder', models.CharField(max_length=255)),
                ('card_last4', models.CharField(max_length=4)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('executive', 'Executive Room'), ('executive_triple', 'Executive Triple Room'), ('executive_suite', 'Executive Suite'), ('deluxe_suite', 'Deluxe Suite'), ('presidential_suite', 'Presidential Suite')], max_length=30)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('total_rooms', models.PositiveIntegerField(default=20)),
                ('available_rooms', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
